version: '3.8'
services:
  iptv-app:
    build: .
    container_name: iptv-player
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: iptv-nginx
    ports:
      - "8587:80"
      - "8588:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:rw
    depends_on:
      - iptv-app
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
    restart: unless-stopped