version: '3.8'
services:
  iptv-app:
    build: .
    container_name: iptv-player
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: iptv-nginx
    ports:
      - "8587:80"
      - "8588:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - iptv-app
    restart: unless-stopped